# Simple workflow for deploying static content to Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["master"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Étape d'installation des dépendances Node.js si applicable
      - name: Install dependencies
        run: npm install

      # Étape de build (génère les fichiers statiques dans ./dist ou autre)
      - name: Build the project
        run: npm run build  # Remplacez par la commande de build appropriée

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Spécifiez le bon répertoire de build
          path: './dist'  # Ajustez ce chemin pour pointer vers votre répertoire de build
          name: github-pages-artifact

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          artifact-name: github-pages-artifact
